### ISSUE TITLE
Check length and handle varints

### ISSUE THREAD

**Issue by Stebalien** [changjiashuai/kotlin-multihash#2]
https://github.com/changjiashuai/kotlin-multihash/blob/cd5c813a7ace09896c97e6441271120173539f93/src/main/kotlin/io/ipfs/multiformats/multihash/Multihash.kt#L23

Both the hash type and the length are varints (https://github.com/ipfs/go-ipfs/issues/4197). While the constructor will usually just treat these as "unsupported" (as far as I can tell), large identity multihash's will fail badly (you'll get garbage at the beginning of the hash).

**Comment by changjiashuai** [comment]
Refactor in v1.1.0
